dialect = [
    'your', 'will', 'with', 'that', 'this', 'from', 'what', 'need', 'there', 'other',
    'barrio', 'even', 'when', 'they', 'have', 'where', 'their', 'some', 'away', 'water',
    'living', 'participant', 'safety', 'only', 'here', 'sound', 'level', 'about', 'after',
    'space', 'sure', 'them', 'which', 'fire', 'malfare', 'than', 'conditions', 'tent',
    'surviving', 'place', 'respect', 'ping', 'gate', 'toilets', 'practical', 'safer',
    'during', 'more', 'pages', 'look', 'nobodies', 'open', 'norg', 'under', 'consent',
    'spain', 'involved', 'prepared', 'community', 'always', 'mind', 'together', 'back',
    'part', 'remember', 'yourself', 'remem', 'both', 'turn', 'volunteers', 'atnowhere',
    'year', 'rubbish', 'zone', 'bottles', 'risk', 'evel', 'parking', 'emergency',
    'monegros', 'self', 'else', 'each', 'care', 'munity', 'want', 'these', 'rules',
    'vehicles', 'ticket', 'once', 'before', 'including', 'desert', 'share', 'ground',
    'come', 'person', 'running', 'goingnowhere','eryo', 'general', 'ngnowhere', 'code', 'spanish', 'taken', 'right', 'arty', 'evacuation', 'july',
    'last', 'artomobiles', 'free', 'trace', 'behind', 'small', 'plan', 'means', 'tobe', 'group', 'perso',
    'shade', 'friends', 'structures', 'ting', 'better', 'shift', 'welfare', 'enough', 'just', 'cool', 'house',
    'ents', 'plastic', 'hours', 'stay', 'harsh', 'tothe', 'nswer', 'music', 'read', 'projects', 'able', 'items',
    'case', 'allowed', 'someone', 'careful', 'again', 'into', 'child', 'sent', 'hear', 'systems', 'town',
    'hardware', 'ehicle', 'vehicle', 'nowh', 'entry', 'apply', 'fora', 'pack', 'road', 'ther', 'owhere', 'cash',
    'most', 'ofthe', 'experience', 'course', 'might', 'then', 'heck', 'operation', 'leave', 'nment', 'ourselv',
    'leav', 'were', 'youneed', 'play', 'sharing', 'ally', 'family', 'expect', 'same', 'default', 'sing', 'dirt',
    'sometimes', 'camp', 'sort', 'allo', 'innovatio', 'within', 'anish', 'provide', 'noinf', 'lost'
]

unusual_expressions = [
    "Nowhere is a radically different experience",
    "You build the barrios, the art, and the 'artomobiles'",
    "Unlike other festivals, at Nowhere we are intentionally self-organising",
    "There's no 'them'—there's just us, and we're all in it together",
    "Leave no trace—From dust to dust, we leave only footprints",
    "Everything you bring to the desert has the potential to become MOOP (Matter Out Of Place)",
    "Malfare complex (sometimes referred to as just 'Malfare')",
    "We strike all structures, clean and chase down every last piece of MOOP",
    "Perimeter Rangers—Your secret dream is to be a Ranger? Join Perimeter",
    "FIST (For Information and Scheduling of Teams)",
    "Ice Ice Baby (The only thing to buy at Nowhere is ice)",
    "Ohana House—A designated safe and sober space",
    "NoInfo—A central information desk, eagerly providing advice",
    "Safer Space Volunteers—They will wear a blue hat",
    "Barrios are organised camps of people who have decided to live the experience as a group",
    "SHIT Ninjas—The team responsible for toilet maintenance",
    "If it's raining, the last part of the road will be closed and no vehicles will be allowed to drive—no exception",
    "Biohazard Site—Nearby river has chemical runoff from farming",
    "Experience, participate, be. This is all there is, so enjoy it!",
    "At Nowhere, we are free to express ourselves, but we need to get consent",
    "From dirt to dirt is not only for your camp and your tent",
    "This is your Nowhere Survival Guide",
    "Buy all the things, pack all the things, last check before hitting the road",
]